### ISSUE TITLE
Can't update the extension from 0.1.38 to 0.1.41

### ISSUE THREAD

**Issue by MagicAndre1981** [elmahio/ExceptionVisualizer#6] opened 2024-12-29 02:17 UTC
I can't update the extension from 0.1.38 to 0.1.41. Clicking on the VSIX opens Visual Studio Installer telling me everything is up to date

![image](https://github.com/user-attachments/assets/80e09e06-d26b-4a5a-b4ae-f6dab4ac5519)

Clicking on Start opens VS 2022 again which offers me an update of your extension. 

![image](https://github.com/user-attachments/assets/7e3dc0cd-c0cb-43b7-a7b7-ceeb2db4453b)

I use VS 2022 (x64) 17.12.3 on Windows 11 23H2.

**Comment by ThomasArdal** [comment] 2024-12-29 06:58
That's strange. What happens if you click that Update button inside of Visual Studio instead of upgrading through the vsix?

**Comment by MagicAndre1981** [comment] 2024-12-29 07:01
here happens the same. That is why I tried downloading the VSIX and installing the VSIX on my own.

**Comment by ThomasArdal** [comment] 2024-12-29 07:17
Can you try this:

- Launch Visual Studio Installer.
- Click Modify on your Visual Studio version.
- Go to the Individual components tab.
- Search for 'exception'.
- Uncheck the 'Exception Visualizer' (might have a different name if you have an older version).
- Click 'Modify'
- Then install the extension from scratch.

![image](https://github.com/user-attachments/assets/aa33021a-d117-4dec-af40-7941c6ef5c9f)

**Comment by MagicAndre1981** [comment] 2024-12-29 07:20
here is what I see in the log:

> 29.12.2024 08:16:04 - Für die Erweiterung wird ein Upgrade von Version 0.1.38.0 durchgeführt.
> 29.12.2024 08:16:04 - Installiertes Produkt gefunden - Globaler Pfad
> 29.12.2024 08:16:04 - Erweiterungsdetails...
> 29.12.2024 08:16:04 - 	Identifier         : ExceptionVisualizerVsix.59bb613d-3a6f-4cc0-90ae-e31743f8efde
> 29.12.2024 08:16:04 - 	Name               : Exception Visualizer
> 29.12.2024 08:16:04 - 	Author             : elmahio
> 29.12.2024 08:16:04 - 	Version            : 0.1.41.0
> 29.12.2024 08:16:04 - 	Description        : Show a debugger visualizer for exceptions in Visual Studio.
> 29.12.2024 08:16:04 - 	Locale             : en-US
> 29.12.2024 08:16:04 - 	MoreInfoURL        : 
> 29.12.2024 08:16:04 - 	InstalledByMSI     : False
> 29.12.2024 08:16:04 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
> 29.12.2024 08:16:04 - 	SignatureState     : Unsigned
> 29.12.2024 08:16:04 - 	Unterstützte Produkte : 
> 29.12.2024 08:16:04 - 		Microsoft.VisualStudio.Community
> 29.12.2024 08:16:04 - 			Version : [17.12,18.0)
> 29.12.2024 08:16:04 - 			ProductArchitecture : amd64
> 29.12.2024 08:16:04 - 		Microsoft.VisualStudio.Community
> 29.12.2024 08:16:04 - 			Version : [17.12,18.0)
> 29.12.2024 08:16:04 - 			ProductArchitecture : arm64
> 29.12.2024 08:16:04 - 	Verweise           : 
> 29.12.2024 08:16:04 - 	Voraussetzungen    : 
> 29.12.2024 08:16:04 - 		-------------------------------------------------------
> 29.12.2024 08:16:04 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 29.12.2024 08:16:04 - 		Name         : Visual Studio core editor
> 29.12.2024 08:16:04 - 		Version      : [17.12,)
> 29.12.2024 08:16:04 - Signaturdetails...
> 29.12.2024 08:16:04 - 	Extension is not signed.
> 29.12.2024 08:16:04 - **Microsoft.VisualStudio.ExtensionManager.RequiresInstallerException**: Requested operation must be completed using Visual Studio Installer.
> 
> **Multiple targets are currently not supported for this operation; retry with the instance you wish to target on the command line.**
>    bei VSIXInstaller.ExtensionService.HandleExtensibilityType(Nullable`1 extensionType, IList`1 validSKUs, ProcessRestartInformation restartInfo, String extensionPackParentName)
>    bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
>    bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
>    bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    bei VSIXInstaller.App.Initialize()
>    bei System.Threading.Tasks.Task`1.InnerInvoke()
>    bei System.Threading.Tasks.Task.Execute()
> 29.12.2024 08:16:05 - Restarting into Visual Studio Installer at C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe with command line:  "C:\Users\André\Downloads\ExceptionVisualizer.vsix"

**Comment by MagicAndre1981** [comment] 2024-12-29 07:25
> Can you try this:
> 
> * Launch Visual Studio Installer.
> * Click Modify on your Visual Studio version.
> * Go to the Individual components tab.
> * Search for 'exception'.
> * Uncheck the 'Exception Visualizer' (might have a different name if you have an older version).
> * Click 'Modify'
> * Then install the extension from scratch.

this works, but here it also opens the VS Setup UI during setup which I never seen before

![image](https://github.com/user-attachments/assets/66fbc5aa-2266-43e6-a2c1-205e731b7d5e)

**Comment by ThomasArdal** [comment] 2024-12-29 07:34
So, the new version is successfully installed now?

The screenshot you posted in the last comment. Isn't that the same window as the one from your first comment? With *Updates* selected in the first one and *Installed* selected in the last one.

**Comment by ThomasArdal** [comment] 2024-12-29 07:39
> this works, but here it also opens the VS Setup UI during setup which I never seen before

Ah, you mean that the Visual Studio Installer is launched during installation of the extension now?

**Comment by MagicAndre1981** [comment] 2024-12-29 07:44
> Ah, you mean that the Visual Studio Installer is launched during installation of the extension now?

yes, but I was not able to capture a screenshot of this where it showed "installing ExceptionVisualizer".

Any idea what this "_Multiple targets are currently not supported for this operation; retry with the instance you wish to target on the command line_" means?

**Comment by ThomasArdal** [comment] 2024-12-29 09:28
The newest versions of Visual Studio switch to using Visual Studio Installer to install extensions. It would seem that there is some kind of a problem with my extension if installed the "old" way.

As for the message in the log I don't know what that means but I will try to find out the cause of that.

**Comment by ThomasArdal** [comment] 2024-12-29 16:01
The error seems to be a general problem in Visual Studio. See:

https://developercommunity.visualstudio.com/t/Cant-Install-Any-Visual-Studio-Extensio/10458512
https://developercommunity.visualstudio.com/t/Unable-to-update-extensions-or-install-n/10446605
https://developercommunity.visualstudio.com/t/VSIX-installer-cannot-install-any-extens/10475376

I'll close this issue since I don't think there's much I can do to fix it ☺️

**Closed as completed by ThomasArdal** 2024-12-29 16:01 UTC

**Comment by MagicAndre1981** [comment] 2024-12-29 21:35
> The newest versions of Visual Studio switch to using Visual Studio Installer to install extensions. 

I tested several vsix updates and all install with VSIXInstaller.exe, only yours is installed via VS setup

![image](https://github.com/user-attachments/assets/55074ef7-49ba-4c17-8c22-2929fd95464b)

Looks like this happens for new extensions that ue the new extension model from **VisualStudio.Extensibility SDK**

**Comment by ThomasArdal** [comment] 2024-12-29 21:52
Ah ok that makes sense. Thank you for providing that info 👍

**Comment by MagicAndre1981** [comment] 2025-01-13 08:38
> Can you try this:

> * Search for 'exception'.
> * Uncheck the 'Exception Visualizer' (might have a different name if you have an older version).
> * Click 'Modify'
> * Then install the extension from scratch.

this is what I also had to do when trying to update to 0.1.45 . This is very annoying.

**Comment by ThomasArdal** [comment] 2025-01-13 09:29
@MagicAndre1981 <del>I don't hope this is something that is needed on every update 🙈</del> Yeah, me too. I don't see any way to fix this currently. From the other links I provided it seems like this is a general problem with the new types of extensions :(

**Comment by MagicAndre1981** [comment] 2025-01-13 10:44
Can you please submit this to Microsoft as feedback? Maybe they gives this a higher priority if the extension developer itself reports it

**Comment by ThomasArdal** [comment] 2025-01-13 11:56
I tried creating one here: https://github.com/microsoft/VSExtensibility/issues/450

**Comment by MagicAndre1981** [comment] 2025-01-13 13:19
thanks, I'll subscribe to the issue and look what Microsoft responds.

**Comment by MagicAndre1981** [comment] 2025-01-14 06:32
btw, can you please update the readme to list this update issue as a known issue?

**Comment by MagicAndre1981** [comment] 2026-01-08 06:52
ok, I [saw a comment](https://github.com/microsoft/VSExtensibility/issues/450#issuecomment-3425511135) and tried it and it worked.

Calling `ExceptionVisualizer.vsix update` from a cmd prompt updates the extension fine.

**Comment by ThomasArdal** [comment] 2026-01-08 07:46
@MagicAndre1981 That's a good tip 👍🏻 BTW, it looks like the issue is resolved in VS 2026. I just tried to upgrade both through the extension manager in Visual Studio and by double-clicking the VSIX. Both work fine now.

**Comment by MagicAndre1981** [comment] 2026-01-08 09:31
ok, I'm still at VS2022 under Win11 23H2. So I'll create a new VM when 23H2 support ends in november 2026 and go to VS2026

**Comment by MagicAndre1981** [comment] 2026-01-08 11:02
ok, it also works with VS2022 and in the status message of the VS installer page it also tells "Step1: remove extension xyz" and in step 2 it installs the extension in the new version. 

Just saw this when updating a different extension that also uses the new API model.

**Comment by ThomasArdal** [comment] 2026-01-08 11:04
This is excellent. I guess the issue is fixed everywhere then 🎉
