### ISSUE TITLE
Empty window when debugging project that use .Net Framework

### ISSUE THREAD

**Issue by PolarGoose** [elmahio/ExceptionVisualizer#4] opened 2024-12-20 20:54 UTC
Visual Studio version 17.12.3
This problem only reproduces when debugging `.Net Framework` projects.

### How to reproduce:
* Create an empty console app that uses `.Net Framework`
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
</Project>
```
* Add code that throws an exception
```
try
{
    throw new Exception("Exception message");
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message); // <-- Put debug point here
}
```
* During debugging, use ExceptionVisualizer to visualize `ex`.
* The empty window appears:
![image](https://github.com/user-attachments/assets/721d048f-9d17-4564-b9c5-fef3577a8fde)

**Comment by ThomasArdal** [comment] 2024-12-21 15:22
Thank you for reporting this. I will have a look at what is going on after Christmas.

**Comment by ThomasArdal** [comment] 2024-12-26 09:47
It seems like only .NET Core and newer versions of .NET are supported here. The error generated when inspecting an exception in a .NET Framework project is this:

```
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

Unless anyone knows how to fix this issue, I think I will make the extension for .NET Core only.

**Comment by PolarGoose** [comment] 2024-12-26 23:34
> It seems like only .NET Core and newer versions of .NET are supported here

The [Microsoft.VisualStudio.DebuggerVisualizers](https://www.nuget.org/packages/Microsoft.VisualStudio.DebuggerVisualizers/17.6.1032901) doesn't need netstandard 2.1.

Where do you get this error? Is it on the Debugger or Debuggee side?

**Comment by ThomasArdal** [comment] 2024-12-27 11:15
The exception I'm getting happens in the VS extension and is this one:

```
StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
 ---> System.Exception: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClrCustomVisualizerVSHost.VisualizerTargetInternal.<RequestDataAsync>d__16.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.OutOfProcessVisualizers.VisualizerTarget.<RequestDataAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.Extensibility.DebuggerVisualizers.VisualizerObjectSourceClient.RequestDataAsync[TMessage,TResponse](TMessage message, JsonSerializer jsonSerializer, CancellationToken cancellationToken)
   at ExceptionVisualizer.ExceptionUserControl.<ControlLoadedAsync>b__4_0()
RPC server exception:
System.Exception: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClrCustomVisualizerVSHost.VisualizerTargetInternal.<RequestDataAsync>d__16.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.OutOfProcessVisualizers.VisualizerTarget.<RequestDataAsync>d__8.MoveNext()
```

The error show up in the debugger in Visual Studio in this line:

https://github.com/elmahio/ExceptionVisualizer/blob/main/src/ExceptionVisualizer/ExceptionUserControl.cs#L28

But when looking at the stack trace, I'm suspecting this error originates from this method:

https://github.com/elmahio/ExceptionVisualizer/blob/main/src/ExceptionVisualizerSource/ExceptionModelSource.cs#L15

**Comment by PolarGoose** [comment] 2024-12-27 13:51
@ThomasArdal,

Wow, it's a very hard-to-read exception. It would be nice if you could visualize it... ouch :)

Honestly, I think it doesn't get to the [ExceptionModelSource.GetData]( https://github.com/elmahio/ExceptionVisualizer/blob/main/src/ExceptionVisualizerSource/ExceptionModelSource.cs#L15), because this call is not present in the stack trace.
I think it really fails inside [ExceptionUserControl.ControlLoadedAsync](https://github.com/elmahio/ExceptionVisualizer/blob/main/src/ExceptionVisualizer/ExceptionUserControl.cs#L28)

Could you try to change `net core` to `net481` here [ExceptionVisualizer.csproj](https://github.com/elmahio/ExceptionVisualizer/blob/main/src/ExceptionVisualizer/ExceptionVisualizer.csproj#L5)?

What assembly does the Debuggee process try to load? Is it `ExceptionVisualizer.dll` or `ExceptionVisualizerSource.dll`? Because if it is the `ExceptionVisualizer.dll`, then the error can be caused by the fact that ExceptionVisualizer uses `net core` that can't be loaded inside `.Net Framework`. However, `.Net Framework` can be loaded inside `net core`.

**Comment by ThomasArdal** [comment] 2024-12-27 15:04
Changing target framework to `net481` causes a new exception. I'm not sure this is supported. I've followed the sample available here which seem to target .NET 8 and netstandard 2.0 as well: https://github.com/microsoft/VSExtensibility/tree/e597e057e94175bab6e490823f7412e77600eedb/New_Extensibility_Model/Samples/RegexMatchDebugVisualizer

**Comment by PolarGoose** [comment] 2024-12-27 23:48
@ThomasArdal,

Thank you for trying.
You have created a really nice plugin.

Hope Microsoft will fix the API at some point.

**Comment by PolarGoose** [comment] 2024-12-28 03:07
@ThomasArdal,

There is hope :)
I have checked the sample that you mentioned [RegexMatchDebugVisualizer](https://github.com/microsoft/VSExtensibility/tree/e597e057e94175bab6e490823f7412e77600eedb/New_Extensibility_Model/Samples/RegexMatchDebugVisualizer). This sample works properly on `.Net Framework`.

I looked into it. They do this strange thing:
`<ProjectReference Include="..\RegexMatchObjectSource\RegexMatchObjectSource.csproj" ReferenceOutputAssembly="false" />`

But you do it without `ReferenceOutputAssembly="false"`:
`<ProjectReference Include="..\ExceptionVisualizerSource\ExceptionVisualizerSource.csproj" />`

Also, I see that they use a newer version of the `VisualStudio.Extensibility` Nuget packages.

Could you check if it will work if you make these changes?

Sorry to bother you :)

**Comment by PolarGoose** [comment] 2024-12-28 04:27
Abort the mission :)

I have found the root cause. I have created a pull request with the fix: https://github.com/elmahio/ExceptionVisualizer/pull/5

However, there still a possibility that another issue will happen when debugging a clean console app without any dependencies:
```
Error:
StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
 ---> System.Exception: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClrCustomVisualizerVSHost.VisualizerTargetInternal.<RequestDataAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.OutOfProcessVisualizers.VisualizerTarget.<RequestDataAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.Extensibility.DebuggerVisualizers.VisualizerObjectSourceClient.RequestDataAsync[TMessage,TResponse](TMessage message, JsonSerializer jsonSerializer, CancellationToken cancellationToken)
   at ExceptionVisualizer.ExceptionUserControl.<ControlLoadedAsync>b__4_0()
RPC server exception:
System.Exception: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at ClrCustomVisualizerVSHost.VisualizerTargetInternal.<RequestDataAsync>d__16.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.VisualStudio.OutOfProcessVisualizers.VisualizerTarget.<RequestDataAsync>d__8.MoveNext()
````

The problem is that the `Ben.Demystifier` depends on newer versions of .Net Dlls that are not available by default.

**Comment by ThomasArdal** [comment] 2024-12-28 07:49
You were 100% right! 🥳 Thank you so much for finding the root cause of this. I have merged the PR with some additional changes (including updating those NuGet packages). I can confirm the error from `System.Trhreading.Tasks.Extensions` you are seeing when no dependencies are in the console app. At least it's better than the previous solution. I'll think about a way to improve this.

Thanks again! A new extension will be published to the marketplace shortly.

**Comment by ThomasArdal** [comment] 2024-12-28 07:50
@PolarGoose Are you on X and/or Bluesky? I'll announce the new version there and credit you if you'd like.

**Comment by PolarGoose** [comment] 2024-12-28 07:58
@ThomasArdal,

Thank you for processing the pull request. 
I only have a LinkedIn :) I have sent you an invite to connect.
You don't need to mention me in the release notes.

**Comment by ThomasArdal** [comment] 2024-12-28 08:14
I'm the one saying thank you. The new version is live BTW. I will close the issue.

**Closed as completed by ThomasArdal** 2024-12-28 08:14 UTC
